### ISSUE TITLE
Error running

### ISSUE THREAD

**Issue by gatlinnewhouse** [electrickite/system76-driver#1]
```zsh
➜ sudo system76-driver-cli
INFO	product_version: 'galu1'
INFO	wifi_pm_disable: Improve WiFi performance on Battery
INFO	Running 'wifi_pm_disable'
INFO	* Improve WiFi performance on Battery
ERROR	Error running actions:
Traceback (most recent call last):
  File "/usr/bin/system76-driver-cli", line 73, in <module>
    for msg in action_runner.run_iter():
  File "/usr/lib/python3.6/site-packages/system76driver/actions.py", line 188, in run_iter
    action.perform()
  File "/usr/lib/python3.6/site-packages/system76driver/actions.py", line 221, in perform
    self.atomic_write(self.content, self.mode)
  File "/usr/lib/python3.6/site-packages/system76driver/actions.py", line 150, in atomic_write
    fp = open(self.tmp, 'x')
FileNotFoundError: [Errno 2] No such file or directory: '/etc/pm/power.d/wireless.S2D3ZL6LT4Y2RIX2WTLV5EIT'
```

**Comment by gatlinnewhouse** [comment]
It looks like it needs `pm-utils` which I do not have since I run `tlp`.

**Comment by electrickite** [comment]
Correct. The System 76 power management functions require ‘pm-utils’ as noted in the PKGBUILD optional dependencies.

Thanks for the report, but I’m going close this issue since the upstream project is designed for use with ‘pm-utils’
